# Generated by Django 4.2.29 on 2026-03-26 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certificate name', max_length=255)),
                ('certificate_type', models.CharField(choices=[('license', 'Business License'), ('compliance', 'Compliance Certificate'), ('security', 'Security Audit'), ('financial', 'Financial License'), ('iso', 'ISO Certification'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Certificate details')),
                ('document', models.FileField(upload_to='certificates/')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(help_text='Issuing authority', max_length=255)),
                ('certificate_number', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_on_site', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_api_key', models.CharField(blank=True, help_text='Stripe API Key (production)', max_length=255)),
                ('stripe_publishable_key', models.CharField(blank=True, help_text='Stripe Publishable Key', max_length=255)),
                ('paypal_client_id', models.CharField(blank=True, help_text='PayPal Client ID', max_length=255)),
                ('paypal_client_secret', models.CharField(blank=True, help_text='PayPal Client Secret', max_length=255)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('enable_registrations', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('enable_deposits', models.BooleanField(default=True, help_text='Allow deposits')),
                ('enable_withdrawals', models.BooleanField(default=True, help_text='Allow withdrawals')),
                ('enable_two_factor', models.BooleanField(default=True, help_text='Require 2FA for admins')),
                ('enable_ip_whitelist', models.BooleanField(default=False, help_text='Enable IP whitelisting')),
                ('session_timeout_minutes', models.IntegerField(default=30, help_text='Admin session timeout in minutes')),
                ('kyc_required', models.BooleanField(default=True, help_text='KYC required for trading')),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=100, help_text='Minimum deposit amount', max_digits=15)),
                ('maximum_withdrawal', models.DecimalField(decimal_places=2, default=50000, help_text='Maximum daily withdrawal', max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_edit', 'User Edited'), ('user_suspend', 'User Suspended'), ('user_activate', 'User Activated'), ('user_delete', 'User Deleted'), ('deposit_approve', 'Deposit Approved'), ('deposit_reject', 'Deposit Rejected'), ('withdrawal_approve', 'Withdrawal Approved'), ('withdrawal_reject', 'Withdrawal Rejected'), ('kyc_approve', 'KYC Approved'), ('kyc_reject', 'KYC Rejected'), ('loan_approve', 'Loan Approved'), ('loan_reject', 'Loan Rejected'), ('content_create', 'Content Created'), ('content_edit', 'Content Edited'), ('content_delete', 'Content Deleted'), ('certificate_upload', 'Certificate Uploaded'), ('certificate_update', 'Certificate Updated'), ('settings_change', 'Settings Changed'), ('login', 'Admin Login'), ('logout', 'Admin Logout'), ('api_key_generate', 'API Key Generated'), ('other', 'Other Action')], max_length=50)),
                ('description', models.TextField()),
                ('target_id', models.CharField(blank=True, help_text='ID of affected object', max_length=255)),
                ('target_type', models.CharField(blank=True, help_text='Type of affected object', max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('changes_before', models.JSONField(blank=True, default=dict)),
                ('changes_after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='dashboard_a_admin_u_529d79_idx'), models.Index(fields=['action_type', '-created_at'], name='dashboard_a_action__6a8f8f_idx'), models.Index(fields=['-created_at'], name='dashboard_a_created_c489e3_idx')],
            },
        ),
    ]
