# Generated by Django 4.2.29 on 2026-03-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_certificate_sitesettings_adminsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.CharField(default='London, United Kingdom', help_text='Company Address', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_email',
            field=models.EmailField(default='admin@elitewealthcapital.uk', help_text='Primary Company Email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Elite Wealth Capital', help_text='Company Name', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(default='+44-XXX-XXXX-XXX', help_text='Company Phone Number', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_website',
            field=models.URLField(default='https://elitewealthcapital.uk', help_text='Company Website URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='support@elitewealthcapital.uk', help_text='Support Email', max_length=254),
        ),
    ]
