# Generated by Django 4.2.29 on 2026-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sitesettings_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_email',
            field=models.EmailField(default='admin@elitewealthcapita.uk', help_text='Primary Company Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_website',
            field=models.URLField(default='https://elitewealthcapita.uk', help_text='Company Website URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='support@elitewealthcapita.uk', help_text='Support Email', max_length=254),
        ),
    ]
