# Generated by Django 4.2.30 on 2026-05-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_sitesettings_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(default='+47 22 33 44 55', help_text='Company Phone Number', max_length=50),
        ),
    ]
