# Generated by Django 4.2.29 on 2026-03-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='category',
            field=models.CharField(choices=[('crypto', 'Crypto Trading'), ('real_estate', 'Real Estate'), ('oil_gas', 'Oil & Gas'), ('agriculture', 'Agriculture'), ('solar', 'Solar Energy'), ('stocks', 'Global Shares')], default='crypto', help_text='Investment sector', max_length=50),
        ),
    ]
