# Generated by Django 4.2.29 on 2026-03-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_cryptoticker_agentapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], default='crypto', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='crypto_type',
            field=models.CharField(blank=True, choices=[('BANK', 'Bank Transfer'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin'), ('LTC', 'Litecoin')], max_length=10, null=True),
        ),
    ]
