# Generated by Django 4.2.30 on 2026-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_add_payment_method_to_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
