# Generated by Django 4.2.30 on 2026-06-18 04:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0005_withdrawal_confirmation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stocks', 'Stocks & Equities'), ('oil', 'Oil & Energy'), ('agriculture', 'Agricultural Commodities'), ('minerals', 'Minerals & Metals')], max_length=50)),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Average purchase price per share', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Share',
                'verbose_name_plural': 'User Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_user_id_352b49_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_status_ea7393_idx',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_profit',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='profit_paid_at',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmentplan'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='category',
            field=models.CharField(default='crypto', max_length=50),
        ),
        migrations.AddField(
            model_name='usershare',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='investments.asset'),
        ),
        migrations.AddField(
            model_name='usershare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usershare',
            unique_together={('user', 'asset')},
        ),
    ]
