# Generated by Django 4.2.30 on 2026-06-18 04:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_asset_usershare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcard',
            name='card_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=16)),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='cvv',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=3)),
        ),
    ]
