# Generated by Django 4.2.29 on 2026-03-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('starter', 'Starter Plan'), ('advance', 'Advance Plan'), ('intro', 'Intro Plan'), ('region', 'Region Plan'), ('pro', 'Pro Plan'), ('premium', 'Premium Plan'), ('executive', 'Executive Plan'), ('elite', 'Elite Plan'), ('platinum', 'Platinum Plan'), ('diamond', 'Diamond Plan')], default='beginner', max_length=20),
        ),
    ]
