# Generated by Django 4.2.30 on 2026-06-18 04:19

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_balanceadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='card_cvv',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=3)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='card_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=16)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_fa_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=32)),
        ),
    ]
