# Generated by Django 4.2.29 on 2026-03-25 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('residence_permit', 'Residence Permit'), ('voter_id', 'Voter ID'), ('tax_id', 'Tax ID Card')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('issuing_country', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('front_image', models.ImageField(upload_to='kyc/front/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='kyc/back/')),
                ('selfie_image', models.ImageField(upload_to='kyc/selfie/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
