# Generated by Django 4.2.29 on 2026-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='issuing_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
