# Generated by Django 4.2.30 on 2026-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycdocument_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Company name for business accounts', max_length=255),
        ),
    ]
